name: qr_bill
description: A Flutter library for use in the development of Swiss payment QR bills and payment slips.
version: 1.1.0
homepage: https://github.com/gaddobenedetti/qr_bill

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  pdf: ^3.8.3
  qr: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family:  OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf